# Permalinks
permalink:        pretty

# Setup
name: Bijay K Pathak
url:  http://bkpathak.github.io
twitter:  bijay697

# Conversion
markdown: kramdown
highlighter:  rouge
lsi:  false
port: 4000
kramdown:
  parse_block_html: true
  syntax_highlighter: rouge

gems:
  - jekyll-sitemap

exclude:
  - .travis.yml
  - validate.rb
  - README.md
  - Gemfile
  - Gemfile.lock
  - bower_components
  - update-vendor-deps.sh
  - vendor/bundle
  - vendor/bower.json
