# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Bijay K Pathak
tagline:          'Machine Learning, Data Scince, Blogging'
url:              http://bkpathak.github.io
paginate:         1
baseurl:          /
author:
  name:           'Bijay K Pathak'
  url:            https://twitter.com/bijay697
  

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/bkpathak/bkpathak.github.io

# Pages
pages_list:
   About: '/about/'
   Archive: '/archive'
   Feed: '/atom.xml'

# Allow URL Redirects:
# * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
